### ISSUE TITLE
Warning: File /Users/<username>/.android/repositories.cfg could not be loaded.

### ISSUE THREAD

**Issue by stephenjg24-git** [anandbagmar/AppiumJavaSample#2]
Hello,

When this line is executed I see this in the output.

Warning: File /Users/<username>/.android/repositories.cfg could not be loaded.

I altered the script to be like this.

touch ~/.android/repositories.cfg
./sdkmanager "tools" "platform-tools" "platforms;android-28" "build-tools;28.0.3" "info_back"

Stephen

**Comment by anandbagmar** [comment]
Thanks. Updated the script
